image: jangrewe/gitlab-ci-android

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - gist/build/outputs/aar/gist-debug.aar
      - gist/build/outputs/aar/gist-release.aar

deploy_to_gitlab:
  stage: deploy
  image: gradle:6.7-jdk11
  script:
    - 'gradle publish'
  except:
    - master