name: Publish for CI

on:
  push:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Push to Gitlab
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add ci https://AndroidCI:${{ secrets.GITLAB_TOKEN }}@gitlab.com/bourbonltd/gist-android.git
        git push ci --tags