name: Build and publish

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

env:
  IMAGE_NAME: gist-backoffice
  GCP_REGISTRY: eu.gcr.io
  GCP_PROJECT_ID: gist-build

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Build Gist Library
      run: gradle assemble
    - name: Publish Gist Library
      run: gradle publish
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}